//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionBanks.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public long ID { get; set; }
        public int InstituteID { get; set; }
        public int ImportedFileID { get; set; }
        public string Question1 { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Option5 { get; set; }
        public string Option6 { get; set; }
        public Nullable<short> OptionCount { get; set; }
        public string AnswerHint { get; set; }
        public string OptionHint1 { get; set; }
        public string OptionHint2 { get; set; }
        public string OptionHint3 { get; set; }
        public string OptionHint4 { get; set; }
        public string OptionHint5 { get; set; }
        public string OptionHint6 { get; set; }
        public string QuestionInfo { get; set; }
        public bool IsMultichoise { get; set; }
        public short CorrectAnswer { get; set; }
        public bool IsCorrectAnswer1 { get; set; }
        public bool IsCorrectAnswer2 { get; set; }
        public bool IsCorrectAnswer3 { get; set; }
        public bool IsCorrectAnswer4 { get; set; }
        public bool IsCorrectAnswer5 { get; set; }
        public bool IsCorrectAnswer6 { get; set; }
        public int Marks { get; set; }
        public int Time { get; set; }
        public short Complexity { get; set; }
        public int CertificationID { get; set; }
        public int StandardID { get; set; }
        public int SubjectID { get; set; }
        public int TopicID { get; set; }
        public byte[] Image { get; set; }
    }
}
